[build]
  command = "npm install && npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@neondatabase/serverless",
    "@prisma/client",
    "bcryptjs",
    "cors",
    "express",
    "express-session",
    "jsonwebtoken",
    "multer",
    "nodemailer",
    "openai",
    "passport",
    "passport-local",
    "pg",
    "stripe",
    "ws"
  ]

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist/public"
  functions = "netlify/functions"
  functionsPort = 9999 