services:
  - type: web
    name: masjid-nabawi
    env: node
    buildCommand: |
      npm install
      npm install -g vite esbuild
      npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false 